branchName: '${issue.title,}'
gitSafeReplacementChar: '-'
openDraftPR: true
branches:
  - label: nuovo-capitolo
    prefix: add/
  - label: modifica-capitolo
    prefix: patch/
  - label: '*'
    prefix: issues/